### ISSUE TITLE
Messed up rendering

### ISSUE THREAD

**Issue by bjorn3** [zulip/zulip-terminal#1033]
![image](https://user-images.githubusercontent.com/17426603/118296620-7940e400-b4dd-11eb-9cf0-ff53874e1237.png)

ctrl+l doesn't fix this. Itscrolls with the exact message for which it happens.

I also saw ![image](https://user-images.githubusercontent.com/17426603/118296873-ba38f880-b4dd-11eb-8422-8605efb61c96.png) which fixed itself again.

(yellow = all the same person)

**Comment by bjorn3** [comment]
An exception just occured. I don't know if it is related:

![image](https://user-images.githubusercontent.com/17426603/118299554-2ec16680-b4e1-11eb-9961-0c89bc332926.png)

zulip-terminal-thread-exceptions.log:

```
Traceback (most recent call last):
  File "/home/bjorn/.local/lib/python3.7/site-packages/zulipterminal/model.py", line 1266, in poll_for_events
    self.event_actions[event['type']](event)
  File "/home/bjorn/.local/lib/python3.7/site-packages/zulipterminal/model.py", line 840, in _handle_subscription_event
    subscribers.remove(user_id)
ValueError: list.remove(x): x not in list
```

**Comment by neiljp** [comment]
@bjorn3 Are you using the 0.6.0 release or a git version right now?

We improved quote handling since the 0.6.0 release, which should have resolved the issue you posted first.

The exception looks like a separate issue. We can handle it more carefully, though it suggests an internal issue - we're being told someone has unsubscribed from a stream but they aren't marked as subscribed in the first place. It seems unlikely, but are you aware of any specific activity on your server around the time of that bug occurring which we could relate to it?

**Comment by bjorn3** [comment]
I am using the 0.6.0 release. This all happened on the rust-lang zulip, which is quite busy, so I don't know of anything specific that happened around the time the bug occured.

**Comment by bjorn3** [comment]
I see there is a debug mode. Does it work when using multiple zulip-term instances for different servers or will they trample over each other when writing the log file?

**Comment by neiljp** [comment]
@bjorn3 I would suggest trying the git version from `main` - it's fairly stable and has new features.

Regarding debugging I'd suggest chatting on chat.zulip.org in #zulip-terminal rather than in issues - but yes, right now they will trample over each other unless they're running in a different location (other than centralizing config via xdg, I'd like to simplify this too in a similar way).
