### ISSUE TITLE
Crash due to "Read timed out"

### ISSUE THREAD

**Issue by jonjensen** [zulip/zulip-terminal#1270]
I installed the latest `zulip-term` from Git and had a crash within a few minutes. This is on Fedora 37 with Python 3.10.8 from RPM, running in a venv.

My `zulip-terminal-tracebacks.log` contains:

```plain


{e}


HTTPSConnectionPool(host='chat.endpointdev.com', port=443): Read timed out. (read timeout=15.0)
Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib64/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='chat.endpointdev.com', port=443): Read timed out. (read timeout=15.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/cli/run.py", line 513, in main
    ).main()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/core.py", line 682, in main
    self.loop.run()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui.py", line 316, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/views.py", line 933, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/views.py", line 407, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/buttons.py", line 247, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/buttons.py", line 113, in keypress
    self.activate(key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/buttons.py", line 109, in activate
    self.show_function()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/core.py", line 585, in narrow_to_stream
    self._narrow_to(anchor=contextual_message_id, stream=stream_name)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/core.py", line 566, in _narrow_to
    self.model.get_messages(num_before=30, num_after=10, anchor=anchor)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/model.py", line 747, in get_messages
    response = self.client.get_messages(message_filters=request)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulip/__init__.py", line 841, in get_messages
    return self.call_endpoint(url="messages", method="GET", request=message_filters)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulip/__init__.py", line 735, in call_endpoint
    return self.do_api_query(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulip/__init__.py", line 655, in do_api_query
    res = self.session.request(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='chat.endpointdev.com', port=443): Read timed out. (read timeout=15.0)
```

Reporting here based on the encouragement at https://github.com/zulip/zulip-terminal/blob/main/docs/FAQ.md#zulip-term-crashed

**Comment by neiljp** [comment]
@jonjensen Thanks for reporting! Can you reproduce this?

As per the final exceptions, this seems like it was triggered by the server timing out, specifically when you were trying to narrow to a specific stream via the stream list in the left panel - does that fit with what you might have been doing?

I do note that ZT doesn't appear to have exception handling for get-messages, which is the underlying API operation occurring here, which is an improvement we could certainly make.

That said, the final exception appears to be a `ReadTimeout` from `requests`, which is-a `Timeout` exception, which is at least partially handled in the `zulip` python API library ZT uses. I'm unsure if that library should handle or otherwise translate this case to let ZT know what is happening, since generally high-level issues have been treated as such in the past, rather than having to deal with such internal exceptions.

Do you have any specific server details you can share? eg. is it big/small? Was it a big or small stream? New or old server?

Thanks again for reporting!

**Comment by jonjensen** [comment]
The server version is 3.2, feature level 27.

I don't remember which stream I was going into. We have both big and small ones, so could've been either. I think it was caused by network slowness, though, not by the server doing anything slowly. I was using the Zulip web client in a browser to the same server at the same time, and it was fine.

I was able to reproduce the problem on the first try by dropping packets to the server with:

```sh
iptables -A OUTPUT -d chat.endpointdev.com -j DROP
```

Resulting in a crash once the timeout was reached:

```plain


{e}


HTTPSConnectionPool(host='chat.endpointdev.com', port=443): Max retries exceeded with url: /api/v1/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=true&narrow=%5B%5B%22stream%22%2C+%22VisionPort+Fulfillment%22%5D%5D&dont_block=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f002cc71ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f002cc71ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.endpointdev.com', port=443): Max retries exceeded with url: /api/v1/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=true&narrow=%5B%5B%22stream%22%2C+%22VisionPort+Fulfillment%22%5D%5D&dont_block=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f002cc71ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/cli/run.py", line 513, in main
    ).main()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/core.py", line 682, in main
    self.loop.run()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui.py", line 316, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/views.py", line 933, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/views.py", line 407, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/buttons.py", line 247, in keypress
    return super().keypress(size, key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/buttons.py", line 113, in keypress
    self.activate(key)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/ui_tools/buttons.py", line 109, in activate
    self.show_function()
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/core.py", line 585, in narrow_to_stream
    self._narrow_to(anchor=contextual_message_id, stream=stream_name)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/core.py", line 566, in _narrow_to
    self.model.get_messages(num_before=30, num_after=10, anchor=anchor)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulipterminal/model.py", line 747, in get_messages
    response = self.client.get_messages(message_filters=request)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulip/__init__.py", line 841, in get_messages
    return self.call_endpoint(url="messages", method="GET", request=message_filters)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulip/__init__.py", line 735, in call_endpoint
    return self.do_api_query(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/zulip/__init__.py", line 655, in do_api_query
    res = self.session.request(
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/jon/zt_venv/lib64/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.endpointdev.com', port=443): Max retries exceeded with url: /api/v1/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=true&narrow=%5B%5B%22stream%22%2C+%22VisionPort+Fulfillment%22%5D%5D&dont_block=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f002cc71ab0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

Different chain of errors this time, but probably because I totally dropped all packets to the server, whereas before likely only some TCP connections timed out while others could still happen once the network recovered.

HTH!

**Comment by neiljp** [comment]
Thanks!

This is a good reproducer in terms of ZT (or a dependency) being fallible, and again from another `requests` exception unfortunately.

Other than reproducing manually - which is useful to debug the issue - have you experienced the same issue in general use of ZT? I understand it doesn't inspire confidence if this happens early on, but it would be useful to know if this is a rare event. Using `--explore` should keep your unreads, in case you're concerned regarding losing state.

In respect of the original issue, we use the default python zulip library timeout of 15s for these calls, which normally should be sufficient?

Again, not to say that this case shouldn't be handled better, but is your network potentially that congested or slow?

I have observed something like this very infrequently on a different network call, and am following upon on chat.zulip.org.

**Comment by jonjensen** [comment]
I only experienced it once since installing zulip-term and using it on and off for ~6 hours. (I tried zulip-term briefly a few years ago but didn't stick with it, and am trying it again.)

The network I am on is not slow, but I think the route between me and the server had an outage of several seconds and when it recovered either the TCP retry times were long enough to exceed the 15s timeout, or it never would have finished at all because the TCP connection was broken but my network stack never got the message to pass back to Python. Just my best guess.

15s is a plenty long timeout IMO; it's more a question of what happens when it's exceeded. The UI was completely frozen during this time too, so I had no idea what was going on.

Ideally the UI would remain responsive with what data is there locally and show a message at the top saying the network is having trouble. And never panic.

But I know this isn't easy since it has to be done intentionally here vs. the web client where the browser handles all this for us.

Thanks for your responses, and so quick! Zulip is great.

**Comment by exarkun** [comment]
This is happening to me a dozen or more times every day.
