### ISSUE TITLE
ZT crashes when trying to send a new message to an empty stream upon pressing "c."

### ISSUE THREAD

**Issue by rsashank** [zulip/zulip-terminal#1453]
The problem arises in both the stable release and the development environment. The only modification I made was commenting out the line `self.focus_msg = focus_msg` to prevent the "Focus out of range" IndexError. I'm don't think the commented-out line has anything to do with error, but a confirmation would be nice. 

The commented out line is a common fix that was recommended in https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/IndexError.20while.20starting.2E.

**To reproduce the issue:**

1. Navigate to the right column view.
2. Select a user by pressing "Enter," which takes you to the compose box.
3. Press "Esc" to exit the compose box.
4. Press "c."

This sequence of actions crashes ZT.

**Traceback**
```
{e}


None
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/zulipterminal/cli/run.py", line 509, in main
    ).main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/zulipterminal/core.py", line 678, in main
    self.loop.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/zulipterminal/ui.py", line 251, in keypress
    self.middle_column.keypress(size, key)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/zulipterminal/ui_tools/views.py", line 616, in keypress
    self.footer.stream_box_view(caption=stream_dict[stream_id]["name"])
KeyError: None
```

**Comment by rsashank** [comment]
I made a fix for this issue. I'll submit a pull request, and if someone could verify whether the problem is caused by the commented-out line `self.focus_msg = focus_msg`, that would be appreciated.
