### ISSUE TITLE
Nasty error message when starting up ZT while offline

### ISSUE THREAD

**Issue by rht** [zulip/zulip-terminal#216]
```
    Welcome to Zulip.
Loading |Invalid API key
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c6d8>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c6d8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 552, in do_api_query
    **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c6d8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/run/current-system/sw/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/core.py", line 264, in register_initial_desired_events
    apply_markdown=True)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 754, in register
    request=request,
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 619, in call_endpoint
    longpolling=longpolling, files=files)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 582, in do_api_query
    raise ZulipError('cannot connect to server ' + self.base_url)
zulip.ZulipError: cannot connect to server https://chat.zulip.org/api/
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc4356358>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /json/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=false&narrow=%5B%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc4356358>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 552, in do_api_query
    **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /json/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=false&narrow=%5B%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc4356358>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/run/current-system/sw/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/model.py", line 194, in get_messages
    method="GET")
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 582, in do_api_query
    raise ZulipError('cannot connect to server ' + self.base_url)
zulip.ZulipError: cannot connect to server https://chat.zulip.org/api/

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c898>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/users?client_gravatar=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c898>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 552, in do_api_query
    **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/users?client_gravatar=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c898>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/run/current-system/sw/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/model.py", line 63, in _update_realm_users
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 821, in get_members
    request=request,
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 619, in call_endpoint
    longpolling=longpolling, files=files)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 582, in do_api_query
    raise ZulipError('cannot connect to server ' + self.base_url)
zulip.ZulipError: cannot connect to server https://chat.zulip.org/api/

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc439f7b8>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/users/me (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc439f7b8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 552, in do_api_query
    **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/users/me (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc439f7b8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/run/current-system/sw/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/model.py", line 58, in _update_user_id
    self.user_id = self.client.get_profile()['user_id']
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 786, in get_profile
    request=request,
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 619, in call_endpoint
    longpolling=longpolling, files=files)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 582, in do_api_query
    raise ZulipError('cannot connect to server ' + self.base_url)
zulip.ZulipError: cannot connect to server https://chat.zulip.org/api/


Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c400>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/rht/code/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 552, in do_api_query
    **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/run/current-system/sw/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chat.zulip.org', port=443): Max retries exceeded with url: /api/v1/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fc432c400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/model.py", line 227, in _update_initial_data
    client_gravatar=True,
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 754, in register
    request=request,
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 619, in call_endpoint
    longpolling=longpolling, files=files)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip/__init__.py", line 582, in do_api_query
    raise ZulipError('cannot connect to server ' + self.base_url)
zulip.ZulipError: cannot connect to server https://chat.zulip.org/api/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/cli/run.py", line 128, in main
    Controller(zuliprc_path, zterm['theme']).main()
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/core.py", line 32, in __init__
    self.model = Model(self)
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/model.py", line 43, in __init__
    self._update_initial_data()
  File "/home/rht/code/venv/lib/python3.7/site-packages/zulip_term-0.2.1+git-py3.7.egg/zulipterminal/model.py", line 236, in _update_initial_data
    raise urwid.ExitMainLoop()
urwid.main_loop.ExitMainLoop
Zulip Terminal has crashed!
You can ask for help at:
https://chat.zulip.org/#narrow/stream/206-zulip-terminal

Thanks for using the Zulip-Terminal interface.
```

**Comment by neiljp** [comment]
@zulipbot claim

**Comment by neiljp** [comment]
@rht Please check if #217 works for you? The startup time may be affected, but hopefully not noticeably.
