### ISSUE TITLE
0.3.1 startup crash on macOS

### ISSUE THREAD

**Issue by hjiang** [zulip/zulip-terminal#350]
I tried to run 0.3.1 on macOS in a clean virtualenv like the README suggested. But had the following crash on startup:

```
Loading |Traceback (most recent call last):
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/cli/run.py", line 169, in main
    autohide_setting).main()
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/core.py", line 38, in __init__
    self.view = View(self)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui.py", line 35, in __init__
    super(View, self).__init__(self.main_window())
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui.py", line 90, in main_window
    self.center_column = self.message_view()
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui.py", line 43, in message_view
    self.search_box)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 276, in __init__
    msg_list = MessageView(model)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 34, in __init__
    self.set_focus(self.focus_msg)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/urwid/listbox.py", line 578, in set_focus
    raise IndexError("Can't set focus, ListBox is empty")
IndexError: Can't set focus, ListBox is empty
Zulip Terminal has crashed!
```
macOS version: 10.14.4 (18E226)
Python version: 3.7.0

**Comment by neiljp** [comment]
As suggested by @sumanthvrao on #zulip-terminal after a little discussion, this is likely issue #326 

@hjiang Does this occur for fewer muted streams than you currently have?

**Comment by hjiang** [comment]
I created a new organization with the default "general" and "announce" streams on zulipchat.com and ran 0.3.1 with it. It still crashed but with a different stack trace:
```
Loading |Traceback (most recent call last):
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/cli/run.py", line 169, in main
    autohide_setting).main()
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/core.py", line 38, in __init__
    self.view = View(self)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui.py", line 35, in __init__
    super(View, self).__init__(self.main_window())
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui.py", line 90, in main_window
    self.center_column = self.message_view()
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui.py", line 43, in message_view
    self.search_box)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 276, in __init__
    msg_list = MessageView(model)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 27, in __init__
    self.log = urwid.SimpleFocusListWalker(self.main_view())
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 40, in main_view
    msg_btn_list = create_msg_box_list(self.model)
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/utils.py", line 40, in create_msg_box_list
    MessageBox(msg, model, last_msg),
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 146, in __init__
    super(MessageBox, self).__init__(self.main_view())
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 329, in main_view
    recipient_header = self.stream_header()
  File "/Users/hjiang/Code/venv/zulip-term/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 174, in stream_header
    bar_color = self.model.stream_dict[self.stream_id]['color']
KeyError: 131651
```

**Comment by hjiang** [comment]
I ran the HEAD version against the new organization, and it also crashes with a similar trace:
```
Loading |Traceback (most recent call last):
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/cli/run.py", line 238, in main
    autohide_setting).main()
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/core.py", line 38, in __init__
    self.view = View(self)
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui.py", line 39, in __init__
    super(View, self).__init__(self.main_window())
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui.py", line 84, in main_window
    self.center_panel = self.message_view()
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui.py", line 46, in message_view
    self.search_box)
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/views.py", line 281, in __init__
    msg_list = MessageView(model)
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/views.py", line 27, in __init__
    self.log = urwid.SimpleFocusListWalker(self.main_view())
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/views.py", line 40, in main_view
    msg_btn_list = create_msg_box_list(self.model)
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/utils.py", line 41, in create_msg_box_list
    MessageBox(msg, model, last_msg),
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/boxes.py", line 164, in __init__
    super(MessageBox, self).__init__(self.main_view())
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/boxes.py", line 351, in main_view
    recipient_header = self.stream_header()
  File "/Users/hjiang/Code/zulip-terminal/zulipterminal/ui_tools/boxes.py", line 197, in stream_header
    bar_color = self.model.stream_dict[self.stream_id]['color']
KeyError: 131651
```

**Comment by hjiang** [comment]
This also occurs on a Ubuntu 16.04 box, so it's not a macOS-specific issue.

**Comment by gzachv** [comment]
I am also seeing it for Ubuntu 18.04, zulip-term 0.3.1, Python 3.6.8.

**Comment by amanagr** [comment]
@gzachv thanks for reporting. #400 fixes this issue. @neiljp we should do a release after it?

**Comment by neiljp** [comment]
@amanagr This could also be due to the issue fixed by #403.

 @gzachv @hjiang Given the #403 fix is merged, if you are able to try the version from git, you may find it fixes your problem - and also has a lot of updates :) If you do so, please let us know if this does fix the `KeyError` problem.

**Comment by neiljp** [comment]
@gzachv @hjiang It would be useful if you could report whether the recent release (0.4.0) fixes the problems you had.

**Comment by gzachv** [comment]
I no longer see the problem in 0.4.0.

**Comment by hjiang** [comment]
Sorry I missed the earlier message. Just did a fresh install. No longer seeing the crash!

**Comment by neiljp** [comment]
@gzachv @hjiang Thanks for reporting and giving subsequent feedback regarding this issue - I'm closing this given these last two replies, but please don't hesitate to contact us on chat.zulip.org or by opening new issues, if you have other problems.

I hope you enjoy the improvements in the new version, aside from the fixing of this bug!
