### ISSUE TITLE
Crashing upon launch in soup2markup

### ISSUE THREAD

**Issue by stevenleeg** [zulip/zulip-terminal#436]
Hi there,

I just tried installing zulip-terminal via CLI and ran into the following issue after running through the setup prompt:

```
Loading with:
   theme 'default' specified in zuliprc file.
   autohide setting 'autohide' specified with no config.
Welcome to Zulip.
Loading -Traceback (most recent call last):
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/cli/run.py", line 169, in main
    autohide_setting).main()
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/core.py", line 38, in __init__
    self.view = View(self)
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui.py", line 35, in __init__
    super(View, self).__init__(self.main_window())
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui.py", line 90, in main_window
    self.center_column = self.message_view()
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui.py", line 43, in message_view
    self.search_box)
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 276, in __init__
    msg_list = MessageView(model)
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 27, in __init__
    self.log = urwid.SimpleFocusListWalker(self.main_view())
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 40, in main_view
    msg_btn_list = create_msg_box_list(self.model)
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/utils.py", line 40, in create_msg_box_list
    MessageBox(msg, model, last_msg),
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 146, in __init__
    super(MessageBox, self).__init__(self.main_view())
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 385, in main_view
    content = (None, self.soup2markup(soup.find(name='body')))
  File "/Users/steve/Sync/Code/zulip-terminal-venv/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 245, in soup2markup
    for element in soup:
TypeError: 'NoneType' object is not iterable
Zulip Terminal has crashed!
You can ask for help at:
https://chat.zulip.org/#narrow/stream/206-zulip-terminal

Thanks for using the Zulip-Terminal interface.
```

This happens each time I try to run `zulip-chat`. Any ideas as to what might be going wrong?

**Comment by sumanthvrao** [comment]
Thanks for the report @stevenleeg. We have had tonnes of new features and bug report improvements after the last release (`0.3.1`). We are also in the process of doing a `0.4.0` pre-release soon(ish). While I haven't exactly seen similar reports before, based on the traceback, it seems to be an issue with some un-recognised elements while rendering messages content.(Which has improved over time)

Would it be possible for you to upgrade to the current master? Let us still know if the issue persists. You are welcomed to reach out here or on #zulip-terminal stream  (@ [chat.zulip.org](https://chat.zulip.org/#narrow/stream/206-zulip-terminal)).

**Comment by neiljp** [comment]
@stevenleeg To confirm, are you using git-master, or the 0.3.1 pypi release?

**Comment by neiljp** [comment]
@stevenleeg It will be difficult to debug this further without more feedback, so please let us know if you are able to do so.

**Comment by themechanicalcoder** [comment]
@stevenleeg I got the same error in windows 10 powershell 
![image](https://user-images.githubusercontent.com/34737471/71338437-f03aad00-2575-11ea-8235-3493dab5387d.png)</br>
Here is the log file
[zulip-terminal-tracebacks.log](https://github.com/zulip/zulip-terminal/files/3993786/zulip-terminal-tracebacks.log)

**Comment by neiljp** [comment]
@themechanicalcoder The `fcntl` issue in the logfile suggests this is running directly on Windows, which we do not currently support, so it is a crash upon launch, but this is not the same error.

**Comment by neiljp** [comment]
@stevenleeg We need more information about your setup to debug this, and since we've not heard back in some time then I'm going to close this issue, at least for now. If you can let us know more then please reach out to us on chat.zulip.org (#zulip-terminal) or reopen this or another issue.
