### ISSUE TITLE
zulip-term crashes when trying to send private message from user list

### ISSUE THREAD

**Issue by alfonsrv** [zulip/zulip-terminal#677]
Just installed `zulip-term` from the repo. When trying to send a private message to a user from the user list, it crashes with the following error:

```
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=true&narrow=%5B%5B%22pm_with%22%2C+%22user%40domain.tld%22%5D%5D HTTP/1.1" 200 None
INFO:root:

Already in editor mode


ERROR:root:Already in editor mode
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/cli/run.py", line 299, in main
    **boolean_settings).main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/core.py", line 300, in main
    self.loop.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/raw_display.py", line 417, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui.py", line 212, in keypress
    return super().keypress(size, key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/container.py", line 2310, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/container.py", line 1621, in keypress
    key = self.focus.keypress(tsize, key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/container.py", line 2310, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui_tools/views.py", line 637, in keypress
    return super().keypress(size, key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/listbox.py", line 955, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui_tools/buttons.py", line 84, in keypress
    return super().keypress(size, key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui_tools/buttons.py", line 79, in activate
    self.show_function(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui_tools/buttons.py", line 226, in _narrow_with_compose
    self._view.write_box.private_box_view(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 39, in private_box_view
    self.set_editor_mode()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/ui_tools/boxes.py", line 36, in set_editor_mode
    self.view.controller.enter_editor_mode_with(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zulipterminal/core.py", line 52, in enter_editor_mode_with
    assert self._editor is None, "Already in editor mode"
AssertionError: Already in editor mode
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): chat.domain.tld:443
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/messages?anchor=0&num_before=30&num_after=10&apply_markdown=true&use_first_unread_anchor=true&client_gravatar=true&narrow=%5B%5D HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "POST /api/v1/register HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): chat.domain.tld:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (3): chat.domain.tld:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (4): chat.domain.tld:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (5): chat.domain.tld:443
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/31/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/13/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/30/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/14/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/16/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/21/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/9/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/29/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/7/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/28/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/4/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/19/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/8/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/26/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/12/topics HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://chat.domain.tld:443 "GET /api/v1/users/me/24/topics HTTP/1.1" 200 None
```  

Selection is done with navigating on the user in the user list using arrows and then pressing enter to try and initiate a private message.

**Comment by neiljp** [comment]
@alfonsrv Thanks for the bug report! This error existed previously but was only made evident by a recent refactoring commit exposing this issue. Are you able to test if the commit I just pushed to a branch fixes your issue?
