### ISSUE TITLE
Zulip crashes on pressing 'n' 

### ISSUE THREAD

**Issue by Rohitth007** [zulip/zulip-terminal#957]
**OS**: Ubuntu 20.04
**Terminal**: Gnome-Term 3.36.2
**Shell**: Bash running inside **_TMUX_**

Zulip crashes instead of going to the **'Next Unread Topic'** when pressing the hotkey **'n'**.
_**TMUX**_ might be a reason too.

Output of `zulip-terminal-tracebacks.log`
```python
{e}


Invalid stream name.
Traceback (most recent call last):
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/cli/run.py", line 434, in main
    Controller(zuliprc_path,
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/core.py", line 416, in main
    self.loop.run()
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/rohitth007/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/ui.py", line 191, in keypress
    self.middle_column.keypress(size, key)
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/ui_tools/views.py", line 582, in keypress
    self.controller.narrow_to_topic(
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/core.py", line 327, in narrow_to_topic
    self._narrow_to(
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/core.py", line 285, in _narrow_to
    already_narrowed = self.model.set_narrow(**narrow)
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/model.py", line 214, in set_narrow
    self.stream_id = self.stream_id_from_name(stream)
  File "/home/rohitth007/.local/lib/python3.8/site-packages/zulipterminal/model.py", line 802, in stream_id_from_name
    raise RuntimeError("Invalid stream name.")
RuntimeError: Invalid stream name.
```

**Comment by neiljp** [comment]
@Rohitth007 While the behavior of `n` is not perfect, this should avoid the crash issue and return to the previous behavior - it'd be great to know if you agree :+1:
